INSERT INTO usuario (nome,email,senha,papel,logado) VALUES ('Augusto','a','123123','USER',false)
INSERT INTO usuario (nome,email,senha,papel,logado) VALUES ('Joao','a@gmail.com','123123','USER',false)
INSERT INTO usuario (nome,email,senha,papel,logado) VALUES ('Carlos','b@gmail.com','123123','USER',false)
INSERT INTO usuario (nome,email,senha,papel,logado) VALUES ('Maria','c@gmail.com','123123','USER',false)
INSERT INTO usuario (nome,email,senha,papel,logado) VALUES ('Joaquina','d@gmail.com','123123','USER',false)
INSERT INTO usuario (nome,email,senha,papel,logado) VALUES ('Fabio','e@gmail.com','123123','USER',false)
INSERT INTO usuario (nome,email,senha,papel,logado) VALUES ('Gil','f@gmail.com','123123','USER',false)
INSERT INTO usuario (nome,email,senha,papel,logado) VALUES ('Cristiano','g@gmail.com','123123','USER',false)
INSERT INTO usuario (nome,email,senha,papel,logado) VALUES ('Roger','h@gmail.com','123123','USER',false)

INSERT INTO amigo VALUES (NULL,2,1)
INSERT INTO amigo VALUES (NULL,3,1)
INSERT INTO amigo VALUES (NULL,4,1)
INSERT INTO amigo VALUES (NULL,5,1)
INSERT INTO amigo VALUES (NULL,6,1)
INSERT INTO amigo VALUES (NULL,7,1)
INSERT INTO amigo VALUES (NULL,8,1)
